"use client";

import { useEffect, useMemo, useState } from "react";
import { questions, services, type DiagnosticOutcome } from "../data/diagnosticFlow";

const SUPPORT_EMAIL = "hello@nordicstudio.com";

interface IssueSummaryProps {
  answers: Record<string, string>;
  history: string[];
  outcome: DiagnosticOutcome;
  onRestart: () => void;
}

function getIssueTypeLabel(answers: Record<string, string>, history: string[]) {
  const firstQuestionId = history[0];
  const firstAnswerId = answers[firstQuestionId];
  const firstQuestion = firstQuestionId ? questions[firstQuestionId] : null;
  const firstAnswer = firstQuestion?.options.find((option) => option.id === firstAnswerId);
  return firstAnswer?.label ?? "Not specified";
}

export function generateSummary(
  answers: Record<string, string>,
  history: string[],
  outcome: DiagnosticOutcome,
): string {
  const timestamp = new Date().toLocaleString();
  const service = services[outcome.serviceId as keyof typeof services];

  const qaLines = history
    .filter((questionId) => answers[questionId])
    .map((questionId) => {
      const question = questions[questionId];
      const answer = question?.options.find((option) => option.id === answers[questionId]);
      if (!question || !answer) {
        return null;
      }
      return `Q: ${question.title}\nA: ${answer.label} - ${answer.description}`;
    })
    .filter((line): line is string => Boolean(line))
    .join("\n\n");

  const nextStepsList = outcome.nextSteps.map((step, index) => `${index + 1}. ${step}`).join("\n");

  return `SUPPORT REQUEST - ${timestamp}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ISSUE TYPE: ${getIssueTypeLabel(answers, history)}
DIAGNOSED SEVERITY: ${outcome.urgency.toUpperCase()}
RECOMMENDED SERVICE: ${service?.name ?? "Unknown service"}

USER REPORTED:
${qaLines}

RECOMMENDED RESPONSE TIMEFRAME:
${outcome.estimatedTimeframe}

NEXT STEPS AGREED:
${nextStepsList}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by the Diagnosis Wizard`;
}

function getBookingLabel(urgency: DiagnosticOutcome["urgency"]) {
  if (urgency === "critical") {
    return "Book Emergency Call ->";
  }
  if (urgency === "low") {
    return "Book Free Consultation ->";
  }
  if (urgency === "high") {
    return "Book Paid Consultation ->";
  }
  return "Book Consultation ->";
}

function renderCodeLine(line: string) {
  const labelMatch = /^([A-Z ]+):(.*)$/.exec(line);
  if (!labelMatch) {
    return <span>{line || " "}</span>;
  }

  return (
    <>
      <span className="v21-summary-key">{labelMatch[1]}:</span>
      <span>{labelMatch[2]}</span>
    </>
  );
}

export default function IssueSummary({ answers, history, outcome, onRestart }: IssueSummaryProps) {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!copied) {
      return;
    }
    const timer = window.setTimeout(() => setCopied(false), 1700);
    return () => window.clearTimeout(timer);
  }, [copied]);

  const service = services[outcome.serviceId as keyof typeof services];
  const summaryText = useMemo(() => generateSummary(answers, history, outcome), [answers, history, outcome]);
  const summaryLines = useMemo(() => summaryText.split("\n"), [summaryText]);
  const subject = `Support Request - ${outcome.urgency.toUpperCase()} - ${service?.name ?? "Service"}`;
  const mailtoHref = `mailto:${SUPPORT_EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(summaryText)}`;
  const bookingHref = `mailto:${SUPPORT_EMAIL}?subject=${encodeURIComponent(`Booking - ${service?.name ?? "Consultation"}`)}`;

  const handleCopy = async () => {
    if (!navigator.clipboard?.writeText) {
      return;
    }
    try {
      await navigator.clipboard.writeText(summaryText);
      setCopied(true);
    } catch {
      setCopied(false);
    }
  };

  return (
    <section className="v21-summary-shell" aria-label="Generated issue summary">
      <h3>Issue Summary</h3>

      <div className="v21-summary-code hide-native-scrollbar">
        {summaryLines.map((line, index) => (
          <div className="v21-summary-line" key={`${line}-${index}`}>
            <span className="v21-summary-line-number">{index + 1}</span>
            <span className="v21-summary-line-content">{renderCodeLine(line)}</span>
          </div>
        ))}
      </div>

      <div className="v21-summary-actions">
        <button type="button" className="v21-summary-btn is-primary" onClick={handleCopy}>
          Copy Summary
        </button>
        <a className="v21-summary-btn is-outline" href={mailtoHref}>
          Send via Email
        </a>
        <button type="button" className="v21-summary-btn is-ghost" onClick={onRestart}>
          Start Over
        </button>
      </div>

      <p className={`v21-summary-toast${copied ? " is-visible" : ""}`} role="status" aria-live="polite">
        Summary copied ✓
      </p>

      <a className="v21-booking-cta" href={bookingHref}>
        {getBookingLabel(outcome.urgency)}
      </a>
    </section>
  );
}

